name: Deploy site

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Compute projects cache key
        id: cache-key
        run: echo "day=$(date -u +%Y-%m-%d)" >> "$GITHUB_OUTPUT"

      - name: Restore projects cache
        id: projects-cache
        uses: actions/cache@v4
        with:
          path: src/data/projects.json
          key: projects-${{ github.repository_owner }}-${{ steps.cache-key.outputs.day }}
          restore-keys: |
            projects-${{ github.repository_owner }}-

      - name: Install dependencies
        run: npm ci

      - name: Fetch projects
        if: github.event_name != 'schedule' || steps.projects-cache.outputs.cache-hit != 'true'
        run: npm run fetch-projects
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: withastro/action@v1
        with:
          deploy_branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
